import type { Analysis, Trace, VizPlan } from "@oocc/contracts";

/**
 * The twelve committed fixtures (docs/PRD.md §2.2, fixtures/README.md).
 * Phase 1 has no backend: this list is the dev-only fixture picker's menu,
 * and also the allowlist `fetchFixture` validates against before fetching
 * `/fixtures-data/<name>.json` (a static asset — see that function's
 * docstring for why it isn't a Route Handler).
 */
export const FIXTURE_NAMES = [
  "bubble_sort",
  "binary_search",
  "fibonacci_recursion",
  "bfs_graph",
  "linked_list_reversal",
  "two_sum",
  "quicksort_partition",
  "n_queens",
  "dp_knapsack",
  "infinite_loop",
  "throws",
  "large_trace_40k",
] as const;

/**
 * The Phase 4 C++ fixtures (docs/PRD.md §3.5, fixtures/cpp/) — a second,
 * separate list rather than appended to FIXTURE_NAMES above: that array
 * and fixtures/README.md's "twelve" are the shared, append-only Python
 * set (CLAUDE.md), and this is deliberately not another silent addition
 * to it. Regenerate with fixtures/cpp/generate.py after editing any
 * fixtures/cpp/programs/*.cpp source or the runtime/pass it's compiled
 * against, then `pnpm --filter @oocc/web gen:fixtures-data` to refresh
 * public/fixtures-data/.
 */
export const CPP_FIXTURE_NAMES = [
  "linked_list_reversal_cpp",
  "vector_sort_cpp",
  "bst_insert_cpp",
  "dfs_adjacency_list_cpp",
  "pointer_aliasing_cpp",
  "out_of_bounds_write_cpp",
  "two_sum_cpp",
  "fibonacci_recursion_cpp",
  "quicksort_partition_cpp",
  "n_queens_cpp",
  "dp_knapsack_cpp",
] as const;

export type FixtureName = (typeof FIXTURE_NAMES)[number] | (typeof CPP_FIXTURE_NAMES)[number];

export function isFixtureName(value: string): value is FixtureName {
  return (
    (FIXTURE_NAMES as readonly string[]).includes(value) || (CPP_FIXTURE_NAMES as readonly string[]).includes(value)
  );
}

export interface FixtureBundle {
  name: FixtureName;
  trace: Trace;
  source: string;
  analysis: Analysis;
  plan: VizPlan;
}

/**
 * Fetches a fixture's trace + source + analysis + plan from
 * `/fixtures-data/<name>.json` — a plain static asset under
 * `apps/web/public/`, generated by `pnpm --filter @oocc/web gen:fixtures-data`
 * (`apps/web/scripts/sync-fixtures-data.mjs`) and committed.
 *
 * This used to be a Route Handler (`/api/fixtures/[name]`) reading the
 * same data via `fs.readFile` at request time, with
 * `outputFileTracingIncludes` telling Vercel's build to bundle the
 * directory it read from. That still 500'd on the real Vercel deployment
 * even after the data itself was moved inside apps/web (fixing the
 * separate Root Directory problem an earlier version of this comment
 * described) — output file tracing is a heuristic on top of a
 * runtime-computed path, and Vercel's actual behavior here was never
 * directly testable from this sandbox (no way to run a real Vercel
 * build). A static asset under `public/` has none of that: Next.js/Vercel
 * always deploys `public/` verbatim, unconditionally, so there's no
 * tracing/bundling step left to get wrong. This return shape still
 * matches what `POST /api/runs` returns (apps/api/app/routers/runs.py) —
 * swapping the transport for the real API later is still a one-line
 * change in this function, not a shape change at every call site.
 */
export async function fetchFixture(name: FixtureName): Promise<FixtureBundle> {
  const response = await fetch(`/fixtures-data/${name}.json`);
  if (!response.ok) {
    throw new Error(`Failed to load fixture "${name}": HTTP ${response.status}`);
  }
  const data = (await response.json()) as {
    trace: Trace;
    source: string;
    analysis: Analysis;
    plan: VizPlan;
  };
  return { name, trace: data.trace, source: data.source, analysis: data.analysis, plan: data.plan };
}
