"""Validates every committed fixture in fixtures/*.trace.json against
trace.schema.json. Fixtures are generated by fixtures/generator/run_all.py
(see fixtures/README.md) but this test does not regenerate them — it checks
the committed output, the same files apps/web develops against.
"""

import json
from pathlib import Path

import pytest

from oocc_contracts import validate_trace

FIXTURES_DIR = Path(__file__).resolve().parents[4] / "fixtures"
EXPECTED_FIXTURES = {
    "bubble_sort",
    "binary_search",
    "fibonacci_recursion",
    "bfs_graph",
    "linked_list_reversal",
    "two_sum",
    "quicksort_partition",
    "n_queens",
    "dp_knapsack",
    "infinite_loop",
    "throws",
    "large_trace_40k",
}


def test_all_twelve_named_fixtures_exist() -> None:
    present = {p.stem.removesuffix(".trace") for p in FIXTURES_DIR.glob("*.trace.json")}
    missing = EXPECTED_FIXTURES - present
    assert not missing, f"missing fixtures: {sorted(missing)}"


@pytest.mark.parametrize("name", sorted(EXPECTED_FIXTURES))
def test_fixture_validates_against_trace_schema(name: str) -> None:
    path = FIXTURES_DIR / f"{name}.trace.json"
    data = json.loads(path.read_text())
    trace = validate_trace(data)  # raises ContractValidationError on any violation
    assert trace.steps, "a committed fixture must contain at least one step"


def test_infinite_loop_is_truncated_with_step_limit_status() -> None:
    data = json.loads((FIXTURES_DIR / "infinite_loop.trace.json").read_text())
    assert data["status"] == "step_limit"
    assert data["meta"]["truncated"] is True
    assert len(data["steps"]) == data["meta"]["step_count"]


def test_throws_has_a_populated_error_object() -> None:
    data = json.loads((FIXTURES_DIR / "throws.trace.json").read_text())
    assert data["status"] == "runtime_error"
    assert "error" in data
    assert data["error"]["type"]
    assert data["error"]["message"]
    assert data["steps"], "a failed run is still a valid, playable trace, never an exception"


def test_large_trace_40k_is_actually_large_and_not_truncated() -> None:
    data = json.loads((FIXTURES_DIR / "large_trace_40k.trace.json").read_text())
    assert data["status"] == "ok"
    assert data["meta"]["truncated"] is False
    assert 30_000 <= data["meta"]["step_count"] <= 50_000


def test_every_ok_fixture_is_not_truncated() -> None:
    for name in EXPECTED_FIXTURES - {"infinite_loop"}:
        data = json.loads((FIXTURES_DIR / f"{name}.trace.json").read_text())
        if data["status"] == "ok":
            assert data["meta"]["truncated"] is False, name
